# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bline_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bline(object):
    def setupUi(self, Bline):
        Bline.setObjectName("Bline")
        Bline.resize(803, 526)
        self.centralwidget = QtWidgets.QWidget(Bline)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -20, 801, 581))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setObjectName("stackedWidget")
        self.first = QtWidgets.QWidget()
        self.first.setObjectName("first")
        self.bline_png = QtWidgets.QLabel(self.first)
        self.bline_png.setGeometry(QtCore.QRect(-40, 20, 841, 541))
        self.bline_png.setText("")
        self.bline_png.setPixmap(QtGui.QPixmap("bline.png"))
        self.bline_png.setObjectName("bline_png")
        self.stackedWidget.addWidget(self.first)
        self.welcome = QtWidgets.QWidget()
        self.welcome.setObjectName("welcome")
        self.bline_png_2 = QtWidgets.QLabel(self.welcome)
        self.bline_png_2.setGeometry(QtCore.QRect(-40, 20, 841, 541))
        self.bline_png_2.setText("")
        self.bline_png_2.setPixmap(QtGui.QPixmap("bline.png"))
        self.bline_png_2.setObjectName("bline_png_2")
        self.login_button = QtWidgets.QPushButton(self.welcome)
        self.login_button.setGeometry(QtCore.QRect(360, 460, 94, 27))
        self.login_button.setObjectName("login_button")
        self.register_button = QtWidgets.QPushButton(self.welcome)
        self.register_button.setGeometry(QtCore.QRect(360, 500, 94, 27))
        self.register_button.setObjectName("register_button")
        self.stackedWidget.addWidget(self.welcome)
        self.registration = QtWidgets.QWidget()
        self.registration.setObjectName("registration")
        self.reg_name = QtWidgets.QTextEdit(self.registration)
        self.reg_name.setGeometry(QtCore.QRect(240, 120, 331, 31))
        self.reg_name.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_name.setObjectName("reg_name")
        self.reg_second_name = QtWidgets.QTextEdit(self.registration)
        self.reg_second_name.setGeometry(QtCore.QRect(240, 160, 331, 31))
        self.reg_second_name.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_second_name.setObjectName("reg_second_name")
        self.reg_email = QtWidgets.QTextEdit(self.registration)
        self.reg_email.setGeometry(QtCore.QRect(240, 200, 331, 31))
        self.reg_email.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_email.setObjectName("reg_email")
        self.reg_password = QtWidgets.QTextEdit(self.registration)
        self.reg_password.setGeometry(QtCore.QRect(240, 240, 331, 31))
        self.reg_password.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_password.setObjectName("reg_password")
        self.reg_password_repeat = QtWidgets.QTextEdit(self.registration)
        self.reg_password_repeat.setGeometry(QtCore.QRect(240, 280, 331, 31))
        self.reg_password_repeat.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_password_repeat.setObjectName("reg_password_repeat")
        self.reg_username = QtWidgets.QTextEdit(self.registration)
        self.reg_username.setGeometry(QtCore.QRect(240, 320, 331, 31))
        self.reg_username.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_username.setObjectName("reg_username")
        self.register_confirm = QtWidgets.QPushButton(self.registration)
        self.register_confirm.setGeometry(QtCore.QRect(360, 370, 94, 27))
        self.register_confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_confirm.setAccessibleName("")
        self.register_confirm.setObjectName("register_confirm")
        self.label = QtWidgets.QLabel(self.registration)
        self.label.setGeometry(QtCore.QRect(170, 130, 64, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.registration)
        self.label_2.setGeometry(QtCore.QRect(140, 170, 91, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.registration)
        self.label_3.setGeometry(QtCore.QRect(170, 210, 64, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.registration)
        self.label_4.setGeometry(QtCore.QRect(160, 250, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.registration)
        self.label_5.setGeometry(QtCore.QRect(113, 290, 111, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.registration)
        self.label_6.setGeometry(QtCore.QRect(153, 330, 71, 20))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.registration)
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.login_username = QtWidgets.QTextEdit(self.login)
        self.login_username.setGeometry(QtCore.QRect(260, 130, 261, 31))
        self.login_username.setObjectName("login_username")
        self.login_password = QtWidgets.QTextEdit(self.login)
        self.login_password.setGeometry(QtCore.QRect(260, 210, 261, 31))
        self.login_password.setObjectName("login_password")
        self.login_username_label = QtWidgets.QLabel(self.login)
        self.login_username_label.setGeometry(QtCore.QRect(360, 100, 81, 19))
        self.login_username_label.setObjectName("login_username_label")
        self.login_password_label = QtWidgets.QLabel(self.login)
        self.login_password_label.setGeometry(QtCore.QRect(360, 180, 81, 19))
        self.login_password_label.setObjectName("login_password_label")
        self.login_submit = QtWidgets.QPushButton(self.login)
        self.login_submit.setGeometry(QtCore.QRect(350, 270, 94, 27))
        self.login_submit.setObjectName("login_submit")
        self.stackedWidget.addWidget(self.login)
        Bline.setCentralWidget(self.centralwidget)

        self.retranslateUi(Bline)
        QtCore.QMetaObject.connectSlotsByName(Bline)

    def retranslateUi(self, Bline):
        _translate = QtCore.QCoreApplication.translate
        Bline.setWindowTitle(_translate("Bline", "MainWindow"))
        self.login_button.setText(_translate("Bline", "Login"))
        self.register_button.setText(_translate("Bline", "Register"))
        self.register_confirm.setText(_translate("Bline", "register"))
        self.label.setText(_translate("Bline", "Name"))
        self.label_2.setText(_translate("Bline", "Second name"))
        self.label_3.setText(_translate("Bline", "Email"))
        self.label_4.setText(_translate("Bline", "Password"))
        self.label_5.setText(_translate("Bline", "Repeat password"))
        self.label_6.setText(_translate("Bline", "Username"))
        self.login_username_label.setText(_translate("Bline", "Username"))
        self.login_password_label.setText(_translate("Bline", "Password"))
        self.login_submit.setText(_translate("Bline", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bline = QtWidgets.QMainWindow()
    ui = Ui_Bline()
    ui.setupUi(Bline)
    Bline.show()
    sys.exit(app.exec_())
