# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bline_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bline(object):
    def setupUi(self, Bline):
        Bline.setObjectName("Bline")
        Bline.resize(803, 526)
        self.centralwidget = QtWidgets.QWidget(Bline)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -20, 801, 581))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setObjectName("stackedWidget")
        self.first = QtWidgets.QWidget()
        self.first.setObjectName("first")
        self.bline_png = QtWidgets.QLabel(self.first)
        self.bline_png.setGeometry(QtCore.QRect(-40, 20, 841, 541))
        self.bline_png.setAutoFillBackground(False)
        self.bline_png.setText("")
        self.bline_png.setPixmap(QtGui.QPixmap("bline.png"))
        self.bline_png.setObjectName("bline_png")
        self.stackedWidget.addWidget(self.first)
        self.welcome = QtWidgets.QWidget()
        self.welcome.setObjectName("welcome")
        self.bline_png_2 = QtWidgets.QLabel(self.welcome)
        self.bline_png_2.setGeometry(QtCore.QRect(-40, 20, 841, 541))
        self.bline_png_2.setText("")
        self.bline_png_2.setPixmap(QtGui.QPixmap("bline.png"))
        self.bline_png_2.setObjectName("bline_png_2")
        self.login_button = QtWidgets.QPushButton(self.welcome)
        self.login_button.setGeometry(QtCore.QRect(360, 460, 94, 27))
        self.login_button.setObjectName("login_button")
        self.register_button = QtWidgets.QPushButton(self.welcome)
        self.register_button.setGeometry(QtCore.QRect(360, 500, 94, 27))
        self.register_button.setObjectName("register_button")
        self.stackedWidget.addWidget(self.welcome)
        self.registration = QtWidgets.QWidget()
        self.registration.setObjectName("registration")
        self.reg_name = QtWidgets.QTextEdit(self.registration)
        self.reg_name.setGeometry(QtCore.QRect(240, 120, 331, 31))
        self.reg_name.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_name.setObjectName("reg_name")
        self.reg_second_name = QtWidgets.QTextEdit(self.registration)
        self.reg_second_name.setGeometry(QtCore.QRect(240, 160, 331, 31))
        self.reg_second_name.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_second_name.setObjectName("reg_second_name")
        self.reg_email = QtWidgets.QTextEdit(self.registration)
        self.reg_email.setGeometry(QtCore.QRect(240, 200, 331, 31))
        self.reg_email.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_email.setObjectName("reg_email")
        self.reg_password = QtWidgets.QTextEdit(self.registration)
        self.reg_password.setGeometry(QtCore.QRect(240, 240, 331, 31))
        self.reg_password.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_password.setObjectName("reg_password")
        self.reg_password_repeat = QtWidgets.QTextEdit(self.registration)
        self.reg_password_repeat.setGeometry(QtCore.QRect(240, 280, 331, 31))
        self.reg_password_repeat.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_password_repeat.setObjectName("reg_password_repeat")
        self.reg_username = QtWidgets.QTextEdit(self.registration)
        self.reg_username.setGeometry(QtCore.QRect(240, 320, 331, 31))
        self.reg_username.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reg_username.setObjectName("reg_username")
        self.register_confirm = QtWidgets.QPushButton(self.registration)
        self.register_confirm.setGeometry(QtCore.QRect(360, 370, 94, 27))
        self.register_confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_confirm.setAccessibleName("")
        self.register_confirm.setObjectName("register_confirm")
        self.label = QtWidgets.QLabel(self.registration)
        self.label.setGeometry(QtCore.QRect(170, 130, 64, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.registration)
        self.label_2.setGeometry(QtCore.QRect(140, 170, 91, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.registration)
        self.label_3.setGeometry(QtCore.QRect(170, 210, 64, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.registration)
        self.label_4.setGeometry(QtCore.QRect(160, 250, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.registration)
        self.label_5.setGeometry(QtCore.QRect(113, 290, 111, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.registration)
        self.label_6.setGeometry(QtCore.QRect(153, 330, 71, 20))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.registration)
        self.registration_result = QtWidgets.QWidget()
        self.registration_result.setObjectName("registration_result")
        self.stackedWidget.addWidget(self.registration_result)
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.login_username = QtWidgets.QTextEdit(self.login)
        self.login_username.setGeometry(QtCore.QRect(260, 130, 261, 31))
        self.login_username.setObjectName("login_username")
        self.login_password = QtWidgets.QTextEdit(self.login)
        self.login_password.setGeometry(QtCore.QRect(260, 210, 261, 31))
        self.login_password.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.login_password.setObjectName("login_password")
        self.login_username_label = QtWidgets.QLabel(self.login)
        self.login_username_label.setGeometry(QtCore.QRect(360, 100, 81, 19))
        self.login_username_label.setObjectName("login_username_label")
        self.login_password_label = QtWidgets.QLabel(self.login)
        self.login_password_label.setGeometry(QtCore.QRect(360, 180, 81, 19))
        self.login_password_label.setObjectName("login_password_label")
        self.login_submit = QtWidgets.QPushButton(self.login)
        self.login_submit.setGeometry(QtCore.QRect(350, 270, 94, 27))
        self.login_submit.setObjectName("login_submit")
        self.stackedWidget.addWidget(self.login)
        self.logged_user = QtWidgets.QWidget()
        self.logged_user.setObjectName("logged_user")
        self.logged_user_bline_label = QtWidgets.QLabel(self.logged_user)
        self.logged_user_bline_label.setGeometry(QtCore.QRect(0, 20, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.logged_user_bline_label.setFont(font)
        self.logged_user_bline_label.setObjectName("logged_user_bline_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.logged_user)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 20, 701, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logged_user_home_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.logged_user_home_button.setObjectName("logged_user_home_button")
        self.horizontalLayout.addWidget(self.logged_user_home_button)
        self.logged_user_profile_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.logged_user_profile_button.setObjectName("logged_user_profile_button")
        self.horizontalLayout.addWidget(self.logged_user_profile_button)
        self.logged_user_money_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.logged_user_money_button.setObjectName("logged_user_money_button")
        self.horizontalLayout.addWidget(self.logged_user_money_button)
        self.logged_user_logout_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.logged_user_logout_button.setObjectName("logged_user_logout_button")
        self.horizontalLayout.addWidget(self.logged_user_logout_button)
        self.logged_user_menu = QtWidgets.QStackedWidget(self.logged_user)
        self.logged_user_menu.setGeometry(QtCore.QRect(109, 69, 691, 471))
        self.logged_user_menu.setObjectName("logged_user_menu")
        self.logged_user_home_screen = QtWidgets.QWidget()
        self.logged_user_home_screen.setObjectName("logged_user_home_screen")
        self.logged_user_welcome_label = QtWidgets.QLabel(self.logged_user_home_screen)
        self.logged_user_welcome_label.setGeometry(QtCore.QRect(140, 0, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.logged_user_welcome_label.setFont(font)
        self.logged_user_welcome_label.setObjectName("logged_user_welcome_label")
        self.logged_user_news_label = QtWidgets.QLabel(self.logged_user_home_screen)
        self.logged_user_news_label.setGeometry(QtCore.QRect(0, 60, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.logged_user_news_label.setFont(font)
        self.logged_user_news_label.setObjectName("logged_user_news_label")
        self.logged_user_menu.addWidget(self.logged_user_home_screen)
        self.logged_user_myprofile_screen = QtWidgets.QWidget()
        self.logged_user_myprofile_screen.setObjectName("logged_user_myprofile_screen")
        self.output_test = QtWidgets.QTextEdit(self.logged_user_myprofile_screen)
        self.output_test.setGeometry(QtCore.QRect(40, 70, 251, 251))
        self.output_test.setAutoFillBackground(True)
        self.output_test.setObjectName("output_test")
        self.label_7 = QtWidgets.QLabel(self.logged_user_myprofile_screen)
        self.label_7.setGeometry(QtCore.QRect(120, 30, 101, 19))
        self.label_7.setObjectName("label_7")
        self.logged_user_menu.addWidget(self.logged_user_myprofile_screen)
        self.logged_user_money_screen = QtWidgets.QWidget()
        self.logged_user_money_screen.setObjectName("logged_user_money_screen")
        self.logged_user_balance_label = QtWidgets.QLabel(self.logged_user_money_screen)
        self.logged_user_balance_label.setGeometry(QtCore.QRect(0, 0, 131, 31))
        self.logged_user_balance_label.setObjectName("logged_user_balance_label")
        self.logged_user_balance_text = QtWidgets.QTextEdit(self.logged_user_money_screen)
        self.logged_user_balance_text.setGeometry(QtCore.QRect(120, 0, 161, 31))
        self.logged_user_balance_text.setObjectName("logged_user_balance_text")
        self.logged_user_transactions_label = QtWidgets.QLabel(self.logged_user_money_screen)
        self.logged_user_transactions_label.setGeometry(QtCore.QRect(0, 50, 131, 31))
        self.logged_user_transactions_label.setObjectName("logged_user_transactions_label")
        self.logged_user_transactions_type_text = QtWidgets.QTextEdit(self.logged_user_money_screen)
        self.logged_user_transactions_type_text.setGeometry(QtCore.QRect(0, 80, 71, 361))
        self.logged_user_transactions_type_text.setObjectName("logged_user_transactions_type_text")
        self.logged_user_money_previous_button = QtWidgets.QPushButton(self.logged_user_money_screen)
        self.logged_user_money_previous_button.setGeometry(QtCore.QRect(0, 440, 91, 27))
        self.logged_user_money_previous_button.setObjectName("logged_user_money_previous_button")
        self.logged_user_money_next_button = QtWidgets.QPushButton(self.logged_user_money_screen)
        self.logged_user_money_next_button.setGeometry(QtCore.QRect(270, 440, 91, 27))
        self.logged_user_money_next_button.setObjectName("logged_user_money_next_button")
        self.logged_user_sendmoney_label = QtWidgets.QLabel(self.logged_user_money_screen)
        self.logged_user_sendmoney_label.setGeometry(QtCore.QRect(490, 60, 81, 19))
        self.logged_user_sendmoney_label.setObjectName("logged_user_sendmoney_label")
        self.logged_user_receiver_label = QtWidgets.QLabel(self.logged_user_money_screen)
        self.logged_user_receiver_label.setGeometry(QtCore.QRect(380, 100, 64, 19))
        self.logged_user_receiver_label.setObjectName("logged_user_receiver_label")
        self.logged_user_amoun_label = QtWidgets.QLabel(self.logged_user_money_screen)
        self.logged_user_amoun_label.setGeometry(QtCore.QRect(380, 140, 71, 19))
        self.logged_user_amoun_label.setObjectName("logged_user_amoun_label")
        self.logged_user_password_label = QtWidgets.QLabel(self.logged_user_money_screen)
        self.logged_user_password_label.setGeometry(QtCore.QRect(380, 180, 71, 19))
        self.logged_user_password_label.setObjectName("logged_user_password_label")
        self.logged_user_receiver_text = QtWidgets.QTextEdit(self.logged_user_money_screen)
        self.logged_user_receiver_text.setGeometry(QtCore.QRect(470, 90, 191, 31))
        self.logged_user_receiver_text.setObjectName("logged_user_receiver_text")
        self.logged_user_amount_text = QtWidgets.QTextEdit(self.logged_user_money_screen)
        self.logged_user_amount_text.setGeometry(QtCore.QRect(470, 130, 191, 31))
        self.logged_user_amount_text.setObjectName("logged_user_amount_text")
        self.logged_user_password_text = QtWidgets.QTextEdit(self.logged_user_money_screen)
        self.logged_user_password_text.setGeometry(QtCore.QRect(470, 170, 191, 31))
        self.logged_user_password_text.setObjectName("logged_user_password_text")
        self.logged_user_money_confirm_button = QtWidgets.QPushButton(self.logged_user_money_screen)
        self.logged_user_money_confirm_button.setGeometry(QtCore.QRect(520, 220, 94, 27))
        self.logged_user_money_confirm_button.setObjectName("logged_user_money_confirm_button")
        self.logged_user_transactions_user_text = QtWidgets.QTextEdit(self.logged_user_money_screen)
        self.logged_user_transactions_user_text.setGeometry(QtCore.QRect(70, 80, 141, 361))
        self.logged_user_transactions_user_text.setObjectName("logged_user_transactions_user_text")
        self.logged_user_transactions_amount_text = QtWidgets.QTextEdit(self.logged_user_money_screen)
        self.logged_user_transactions_amount_text.setGeometry(QtCore.QRect(210, 80, 61, 361))
        self.logged_user_transactions_amount_text.setObjectName("logged_user_transactions_amount_text")
        self.logged_user_transactions_date_text = QtWidgets.QTextEdit(self.logged_user_money_screen)
        self.logged_user_transactions_date_text.setGeometry(QtCore.QRect(270, 80, 91, 361))
        self.logged_user_transactions_date_text.setObjectName("logged_user_transactions_date_text")
        self.logged_user_menu.addWidget(self.logged_user_money_screen)
        self.stackedWidget.addWidget(self.logged_user)
        Bline.setCentralWidget(self.centralwidget)

        self.retranslateUi(Bline)
        QtCore.QMetaObject.connectSlotsByName(Bline)

    def retranslateUi(self, Bline):
        _translate = QtCore.QCoreApplication.translate
        Bline.setWindowTitle(_translate("Bline", "MainWindow"))
        self.login_button.setText(_translate("Bline", "Login"))
        self.register_button.setText(_translate("Bline", "Register"))
        self.register_confirm.setText(_translate("Bline", "register"))
        self.label.setText(_translate("Bline", "Name"))
        self.label_2.setText(_translate("Bline", "Second name"))
        self.label_3.setText(_translate("Bline", "Email"))
        self.label_4.setText(_translate("Bline", "Password"))
        self.label_5.setText(_translate("Bline", "Repeat password"))
        self.label_6.setText(_translate("Bline", "Username"))
        self.login_username_label.setText(_translate("Bline", "Username"))
        self.login_password_label.setText(_translate("Bline", "Password"))
        self.login_submit.setText(_translate("Bline", "Login"))
        self.logged_user_bline_label.setText(_translate("Bline", "Bline"))
        self.logged_user_home_button.setText(_translate("Bline", "Home"))
        self.logged_user_profile_button.setText(_translate("Bline", "My profile"))
        self.logged_user_money_button.setText(_translate("Bline", "Money management"))
        self.logged_user_logout_button.setText(_translate("Bline", "Log out"))
        self.logged_user_welcome_label.setText(_translate("Bline", "Welcome to best betting platform"))
        self.logged_user_news_label.setText(_translate("Bline", "News:"))
        self.label_7.setText(_translate("Bline", "Profile Info"))
        self.logged_user_balance_label.setText(_translate("Bline", "Current balance"))
        self.logged_user_transactions_label.setText(_translate("Bline", "Last transactions"))
        self.logged_user_transactions_type_text.setHtml(_translate("Bline", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.logged_user_money_previous_button.setText(_translate("Bline", "Previous"))
        self.logged_user_money_next_button.setText(_translate("Bline", "Next"))
        self.logged_user_sendmoney_label.setText(_translate("Bline", "Send money"))
        self.logged_user_receiver_label.setText(_translate("Bline", "Receiver"))
        self.logged_user_amoun_label.setText(_translate("Bline", "How much"))
        self.logged_user_password_label.setText(_translate("Bline", "Password"))
        self.logged_user_money_confirm_button.setText(_translate("Bline", "Confirm"))
        self.logged_user_transactions_user_text.setHtml(_translate("Bline", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.logged_user_transactions_amount_text.setHtml(_translate("Bline", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.logged_user_transactions_date_text.setHtml(_translate("Bline", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bline = QtWidgets.QMainWindow()
    ui = Ui_Bline()
    ui.setupUi(Bline)
    Bline.show()
    sys.exit(app.exec_())
